import '@/styles/globals.css';

import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from '@vercel/analytics/next';
import { type Metadata, type Viewport } from 'next';
import { Inter, Manrope } from 'next/font/google';

import AppProviver from '@/app/providers/app_provider';
import { TRPCReactProvider as TRPCAppProvider } from '@/lib/trpc_app/client';

const siteUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'https://fintrack.live';

///! METADATA SETUP
export const metadata: Metadata = {
  title: 'Fintrack',
  description: 'Financial and budgeting tool. Experience AI automated budgeting.',
  metadataBase: new URL(siteUrl),
  // --- Favicon & app icons
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/favicon-32.png', type: 'image/png', sizes: '32x32' },
      { url: '/favicon-16.png', type: 'image/png', sizes: '16x16' },
    ],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }],
  },

  // --- Open Graph (social / link previews — image generated by opengraph-image.tsx) ---
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: siteUrl,
    siteName: 'Fintrack',
    title: 'Fintrack',
    description: 'Financial and budgeting tool. Experience AI automated budgeting.',
  },

  // --- Twitter Card ---
  twitter: {
    card: 'summary_large_image',
    title: 'Fintrack',
    description: 'Financial and budgeting tool. Experience AI automated budgeting.',
  },

  // --- PWA / manifest (optional) ---
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Fintrack',
  },
};

///! VIEWPORT SETUP
export const viewport: Viewport = {
  initialScale: 1,
  maximumScale: 1,
  width: 'device-width',
  userScalable: false,
  viewportFit: 'cover',
  colorScheme: 'dark',
  themeColor: '#0f0f14',
};

///! FONT SETUP
const inetr = Inter({
  subsets: ['latin'],
  variable: '--ft-font-inter',
  display: 'swap',
});
const manrope = Manrope({
  subsets: ['latin'],
  variable: '--ft-font-manrope',
  display: 'swap',
});

// ======================
//  MAIN COMPONENT
// ======================
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inetr.variable} ${manrope.variable}`}>
      <body>
        <TRPCAppProvider>
          <AppProviver>{children}</AppProviver>
        </TRPCAppProvider>
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
