// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: scheduler/scheduler.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "scheduler";

export interface CreateSchedulerReq {
  name: string;
  description: string;
  frequency: string;
}

export interface CreateSchedulerRes {
  id: string;
  name: string;
  description: string;
  frequency: string;
}

export const SCHEDULER_PACKAGE_NAME = "scheduler";

export interface SchedulerServiceClient {
  createScheduler(request: CreateSchedulerReq, metadata?: Metadata): Observable<CreateSchedulerRes>;
}

export interface SchedulerServiceController {
  createScheduler(
    request: CreateSchedulerReq,
    metadata?: Metadata,
  ): Promise<CreateSchedulerRes> | Observable<CreateSchedulerRes> | CreateSchedulerRes;
}

export function SchedulerServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createScheduler"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SchedulerService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SchedulerService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SCHEDULER_SERVICE_NAME = "SchedulerService";
