// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: paginate.proto

 

export const protobufPackage = "";

export interface PaginateResponse {
  page: number;
  limit: number;
  total: number;
  pageSize: number;
  lastPage: number;
}

export const _PACKAGE_NAME = "";
