// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: finance/budget.proto

/* eslint-disable */
import { Category } from "./transaction";

export const protobufPackage = "finance";

export interface Budget {
  id: string;
  name: string;
  amount: number;
  description: string;
  period: string;
  carryOver: boolean;
  alertThreshold: number;
  category: Category | undefined;
  createdAt: string;
  updatedAt: string;
  spent: string;
}

export interface CreateBudgetReq {
  name: string;
  amount: number;
  description?: string | undefined;
  alertThreshold?: number | undefined;
  categorySlug: string;
  month?: number | undefined;
  year?: number | undefined;
  period?: string | undefined;
}

export interface UnbudgetedCategory {
  slug: string;
  name: string;
  color: string;
  icon: string;
  spent: number;
}

export interface GetBudgetsReq {
  /** 0-indexed */
  month: number;
  year: number;
}

export interface GetBudgetsRes {
  budgets: Budget[];
  unbudgeted: UnbudgetedCategory[];
}

export interface GetBudgetReq {
  id: string;
}

export interface BudgetHistoryEntry {
  id: string;
  limit: number;
  startDate: string;
  endDate?: string | undefined;
  createdAt: string;
}

export interface BudgetDetail {
  budget: Budget | undefined;
  history: BudgetHistoryEntry[];
}

export interface SpendingTrendCategory {
  slug: string;
  name: string;
  color: string;
  amount: number;
}

export interface SpendingTrendMonth {
  /** "Jan 2026" */
  label: string;
  /** all-category EXPENSE sum */
  total: number;
  byCategory: SpendingTrendCategory[];
}

export interface GetSpendingTrendReq {
  /** lookback window: 3, 6, or 12 */
  months: number;
}

export interface GetSpendingTrendRes {
  data: SpendingTrendMonth[];
}

export interface UpdateBudgetReq {
  id: string;
  name?: string | undefined;
  amount?: number | undefined;
  description?: string | undefined;
  alertThreshold?: number | undefined;
}

export interface DeleteBudgetReq {
  id: string;
}

export const FINANCE_PACKAGE_NAME = "finance";
