// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: finance/budget.proto

/* eslint-disable */
import { Category } from "./transaction";

export const protobufPackage = "finance";

export interface Budget {
  id: string;
  name: string;
  amount: number;
  description: string;
  period: string;
  carryOver: boolean;
  alertThreshold: number;
  category: Category | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface CreateBudgetReq {
  name: string;
  amount: number;
  description?: string | undefined;
  alertThreshold?: number | undefined;
  categorySlug: string;
  month?: number | undefined;
  year?: number | undefined;
  period?: string | undefined;
}

export interface UpdateBudgetReq {
  id: string;
  name?: string | undefined;
  amount?: number | undefined;
  description?: string | undefined;
  alertThreshold?: number | undefined;
}

export interface DeleteBudgetReq {
  id: string;
}

export const FINANCE_PACKAGE_NAME = "finance";
