// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: finance/budget.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "finance";

export interface CreateBudgetReq {
  name: string;
  description: string;
  amount: string;
  frequency: string;
}

export interface CreateBudgetRes {
  id: string;
  name: string;
  description: string;
  amount: string;
  frequency: string;
}

export const FINANCE_PACKAGE_NAME = "finance";

export interface BudgetServiceClient {
  createBudget(request: CreateBudgetReq, metadata?: Metadata): Observable<CreateBudgetRes>;
}

export interface BudgetServiceController {
  createBudget(
    request: CreateBudgetReq,
    metadata?: Metadata,
  ): Promise<CreateBudgetRes> | Observable<CreateBudgetRes> | CreateBudgetRes;
}

export function BudgetServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createBudget"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("BudgetService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("BudgetService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BUDGET_SERVICE_NAME = "BudgetService";
