// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: finance/finance.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Budget, CreateBudgetReq, DeleteBudgetReq, UpdateBudgetReq } from "./budget";
import {
  Contribution,
  CreateGoalContributionReq,
  CreateGoalReq,
  DeleteGoalContributionReq,
  GetGoalsReq,
  GetGoalsRes,
  Goal,
  GoalReq,
  UpdateGoalContributionReq,
  UpdateGoalReq,
} from "./goal";
import {
  CreateRecurringReq,
  GetRecurringsReq,
  GetRecurringsRes,
  Recurinrg,
  RecurringReq,
  UpdateRecurringReq,
} from "./recurring";
import {
  AddParticipantReq,
  CreateSplitReq,
  GetSplitAggregateRes,
  GetSplitsReq,
  GetSplitsRes,
  ParticipantReq,
  PaySettlementReq,
  SettlementReq,
  Split,
  SplitParticipant,
  SplitReq,
  SplitSettlement,
  UpdateParticipantReq,
  UpdateSplitReq,
} from "./split";
import {
  BatchCreateTransactionsReq,
  BatchCreateTransactionsRes,
  CreateTransactionReq,
  DeleteTransactionReq,
  Empty,
  GetTransactionReq,
  GetTransactionsReq,
  GetTransactionsRes,
  Transaction,
  UpdateTransactionReq,
} from "./transaction";

export const protobufPackage = "finance";

/** finance/finance.proto */

export const FINANCE_PACKAGE_NAME = "finance";

export interface FinanceServiceClient {
  /** Transactions */

  createTransaction(request: CreateTransactionReq, metadata?: Metadata): Observable<Transaction>;

  batchCreateTransactions(
    request: BatchCreateTransactionsReq,
    metadata?: Metadata,
  ): Observable<BatchCreateTransactionsRes>;

  getTransactions(request: GetTransactionsReq, metadata?: Metadata): Observable<GetTransactionsRes>;

  getTransaction(request: GetTransactionReq, metadata?: Metadata): Observable<Transaction>;

  updateTransaction(request: UpdateTransactionReq, metadata?: Metadata): Observable<Transaction>;

  deleteTransaction(request: DeleteTransactionReq, metadata?: Metadata): Observable<Empty>;

  /** Budgets */

  createBudget(request: CreateBudgetReq, metadata?: Metadata): Observable<Budget>;

  updateBudget(request: UpdateBudgetReq, metadata?: Metadata): Observable<Budget>;

  deleteBudget(request: DeleteBudgetReq, metadata?: Metadata): Observable<Empty>;

  /** Recurring */

  createRecurring(request: CreateRecurringReq, metadata?: Metadata): Observable<Recurinrg>;

  getRecurrings(request: GetRecurringsReq, metadata?: Metadata): Observable<GetRecurringsRes>;

  getRecurring(request: RecurringReq, metadata?: Metadata): Observable<Recurinrg>;

  updateRecurring(request: UpdateRecurringReq, metadata?: Metadata): Observable<Recurinrg>;

  toggleRecurring(request: RecurringReq, metadata?: Metadata): Observable<Recurinrg>;

  deleteRecurring(request: RecurringReq, metadata?: Metadata): Observable<Empty>;

  /** Splits */

  createSplit(request: CreateSplitReq, metadata?: Metadata): Observable<Split>;

  getSplitAggregate(request: Empty, metadata?: Metadata): Observable<GetSplitAggregateRes>;

  getSplits(request: GetSplitsReq, metadata?: Metadata): Observable<GetSplitsRes>;

  getSplit(request: SplitReq, metadata?: Metadata): Observable<Split>;

  updateSplit(request: UpdateSplitReq, metadata?: Metadata): Observable<Split>;

  deleteSplit(request: SplitReq, metadata?: Metadata): Observable<Empty>;

  addParticipant(request: AddParticipantReq, metadata?: Metadata): Observable<SplitParticipant>;

  updateParticipant(request: UpdateParticipantReq, metadata?: Metadata): Observable<SplitParticipant>;

  deleteParticipant(request: ParticipantReq, metadata?: Metadata): Observable<Empty>;

  paySettlement(request: PaySettlementReq, metadata?: Metadata): Observable<SplitSettlement>;

  deleteSettlement(request: SettlementReq, metadata?: Metadata): Observable<Empty>;

  /** Goals */

  createGoal(request: CreateGoalReq, metadata?: Metadata): Observable<Goal>;

  getGoals(request: GetGoalsReq, metadata?: Metadata): Observable<GetGoalsRes>;

  getGoal(request: GoalReq, metadata?: Metadata): Observable<Goal>;

  updateGoal(request: UpdateGoalReq, metadata?: Metadata): Observable<Goal>;

  deleteGoal(request: GoalReq, metadata?: Metadata): Observable<Empty>;

  contributeToGoal(request: CreateGoalContributionReq, metadata?: Metadata): Observable<Contribution>;

  updateGoalContribution(request: UpdateGoalContributionReq, metadata?: Metadata): Observable<Contribution>;

  deleteContribution(request: DeleteGoalContributionReq, metadata?: Metadata): Observable<Empty>;
}

export interface FinanceServiceController {
  /** Transactions */

  createTransaction(
    request: CreateTransactionReq,
    metadata?: Metadata,
  ): Promise<Transaction> | Observable<Transaction> | Transaction;

  batchCreateTransactions(
    request: BatchCreateTransactionsReq,
    metadata?: Metadata,
  ): Promise<BatchCreateTransactionsRes> | Observable<BatchCreateTransactionsRes> | BatchCreateTransactionsRes;

  getTransactions(
    request: GetTransactionsReq,
    metadata?: Metadata,
  ): Promise<GetTransactionsRes> | Observable<GetTransactionsRes> | GetTransactionsRes;

  getTransaction(
    request: GetTransactionReq,
    metadata?: Metadata,
  ): Promise<Transaction> | Observable<Transaction> | Transaction;

  updateTransaction(
    request: UpdateTransactionReq,
    metadata?: Metadata,
  ): Promise<Transaction> | Observable<Transaction> | Transaction;

  deleteTransaction(request: DeleteTransactionReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  /** Budgets */

  createBudget(request: CreateBudgetReq, metadata?: Metadata): Promise<Budget> | Observable<Budget> | Budget;

  updateBudget(request: UpdateBudgetReq, metadata?: Metadata): Promise<Budget> | Observable<Budget> | Budget;

  deleteBudget(request: DeleteBudgetReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  /** Recurring */

  createRecurring(
    request: CreateRecurringReq,
    metadata?: Metadata,
  ): Promise<Recurinrg> | Observable<Recurinrg> | Recurinrg;

  getRecurrings(
    request: GetRecurringsReq,
    metadata?: Metadata,
  ): Promise<GetRecurringsRes> | Observable<GetRecurringsRes> | GetRecurringsRes;

  getRecurring(request: RecurringReq, metadata?: Metadata): Promise<Recurinrg> | Observable<Recurinrg> | Recurinrg;

  updateRecurring(
    request: UpdateRecurringReq,
    metadata?: Metadata,
  ): Promise<Recurinrg> | Observable<Recurinrg> | Recurinrg;

  toggleRecurring(request: RecurringReq, metadata?: Metadata): Promise<Recurinrg> | Observable<Recurinrg> | Recurinrg;

  deleteRecurring(request: RecurringReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  /** Splits */

  createSplit(request: CreateSplitReq, metadata?: Metadata): Promise<Split> | Observable<Split> | Split;

  getSplitAggregate(
    request: Empty,
    metadata?: Metadata,
  ): Promise<GetSplitAggregateRes> | Observable<GetSplitAggregateRes> | GetSplitAggregateRes;

  getSplits(
    request: GetSplitsReq,
    metadata?: Metadata,
  ): Promise<GetSplitsRes> | Observable<GetSplitsRes> | GetSplitsRes;

  getSplit(request: SplitReq, metadata?: Metadata): Promise<Split> | Observable<Split> | Split;

  updateSplit(request: UpdateSplitReq, metadata?: Metadata): Promise<Split> | Observable<Split> | Split;

  deleteSplit(request: SplitReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  addParticipant(
    request: AddParticipantReq,
    metadata?: Metadata,
  ): Promise<SplitParticipant> | Observable<SplitParticipant> | SplitParticipant;

  updateParticipant(
    request: UpdateParticipantReq,
    metadata?: Metadata,
  ): Promise<SplitParticipant> | Observable<SplitParticipant> | SplitParticipant;

  deleteParticipant(request: ParticipantReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  paySettlement(
    request: PaySettlementReq,
    metadata?: Metadata,
  ): Promise<SplitSettlement> | Observable<SplitSettlement> | SplitSettlement;

  deleteSettlement(request: SettlementReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  /** Goals */

  createGoal(request: CreateGoalReq, metadata?: Metadata): Promise<Goal> | Observable<Goal> | Goal;

  getGoals(request: GetGoalsReq, metadata?: Metadata): Promise<GetGoalsRes> | Observable<GetGoalsRes> | GetGoalsRes;

  getGoal(request: GoalReq, metadata?: Metadata): Promise<Goal> | Observable<Goal> | Goal;

  updateGoal(request: UpdateGoalReq, metadata?: Metadata): Promise<Goal> | Observable<Goal> | Goal;

  deleteGoal(request: GoalReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  contributeToGoal(
    request: CreateGoalContributionReq,
    metadata?: Metadata,
  ): Promise<Contribution> | Observable<Contribution> | Contribution;

  updateGoalContribution(
    request: UpdateGoalContributionReq,
    metadata?: Metadata,
  ): Promise<Contribution> | Observable<Contribution> | Contribution;

  deleteContribution(
    request: DeleteGoalContributionReq,
    metadata?: Metadata,
  ): Promise<Empty> | Observable<Empty> | Empty;
}

export function FinanceServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createTransaction",
      "batchCreateTransactions",
      "getTransactions",
      "getTransaction",
      "updateTransaction",
      "deleteTransaction",
      "createBudget",
      "updateBudget",
      "deleteBudget",
      "createRecurring",
      "getRecurrings",
      "getRecurring",
      "updateRecurring",
      "toggleRecurring",
      "deleteRecurring",
      "createSplit",
      "getSplitAggregate",
      "getSplits",
      "getSplit",
      "updateSplit",
      "deleteSplit",
      "addParticipant",
      "updateParticipant",
      "deleteParticipant",
      "paySettlement",
      "deleteSettlement",
      "createGoal",
      "getGoals",
      "getGoal",
      "updateGoal",
      "deleteGoal",
      "contributeToGoal",
      "updateGoalContribution",
      "deleteContribution",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FinanceService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FinanceService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FINANCE_SERVICE_NAME = "FinanceService";
