// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: finance/finance.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Budget, CreateBudgetReq, DeleteBudgetReq, UpdateBudgetReq } from "./budget";
import {
  Contribution,
  CreateGoalContributionReq,
  CreateGoalReq,
  DeleteGoalContributionReq,
  GetGoalsReq,
  GetGoalsRes,
  Goal,
  GoalReq,
  UpdateGoalContributionReq,
  UpdateGoalReq,
} from "./goal";
import {
  CreateRecurringReq,
  GetRecurringsReq,
  GetRecurringsRes,
  Recurinrg,
  RecurringReq,
  UpdateRecurringReq,
} from "./recurring";
import {
  CreateTransactionReq,
  DeleteTransactionReq,
  Empty,
  GetTransactionReq,
  GetTransactionsReq,
  GetTransactionsRes,
  Transaction,
  UpdateTransactionReq,
} from "./transaction";

export const protobufPackage = "finance";

/** finance/finance.proto */

export const FINANCE_PACKAGE_NAME = "finance";

export interface FinanceServiceClient {
  /** Transactions */

  createTransaction(request: CreateTransactionReq, metadata?: Metadata): Observable<Transaction>;

  getTransactions(request: GetTransactionsReq, metadata?: Metadata): Observable<GetTransactionsRes>;

  getTransaction(request: GetTransactionReq, metadata?: Metadata): Observable<Transaction>;

  updateTransaction(request: UpdateTransactionReq, metadata?: Metadata): Observable<Transaction>;

  deleteTransaction(request: DeleteTransactionReq, metadata?: Metadata): Observable<Empty>;

  /** Budgets */

  createBudget(request: CreateBudgetReq, metadata?: Metadata): Observable<Budget>;

  updateBudget(request: UpdateBudgetReq, metadata?: Metadata): Observable<Budget>;

  deleteBudget(request: DeleteBudgetReq, metadata?: Metadata): Observable<Empty>;

  /** Recurring */

  createRecurring(request: CreateRecurringReq, metadata?: Metadata): Observable<Recurinrg>;

  getRecurrings(request: GetRecurringsReq, metadata?: Metadata): Observable<GetRecurringsRes>;

  getRecurring(request: RecurringReq, metadata?: Metadata): Observable<Recurinrg>;

  updateRecurring(request: UpdateRecurringReq, metadata?: Metadata): Observable<Recurinrg>;

  toggleRecurring(request: RecurringReq, metadata?: Metadata): Observable<Recurinrg>;

  deleteRecurring(request: RecurringReq, metadata?: Metadata): Observable<Empty>;

  /** Goals */

  createGoal(request: CreateGoalReq, metadata?: Metadata): Observable<Goal>;

  getGoals(request: GetGoalsReq, metadata?: Metadata): Observable<GetGoalsRes>;

  getGoal(request: GoalReq, metadata?: Metadata): Observable<Goal>;

  updateGoal(request: UpdateGoalReq, metadata?: Metadata): Observable<Goal>;

  deleteGoal(request: GoalReq, metadata?: Metadata): Observable<Empty>;

  contributeToGoal(request: CreateGoalContributionReq, metadata?: Metadata): Observable<Contribution>;

  updateGoalContribution(request: UpdateGoalContributionReq, metadata?: Metadata): Observable<Contribution>;

  deleteContribution(request: DeleteGoalContributionReq, metadata?: Metadata): Observable<Empty>;
}

export interface FinanceServiceController {
  /** Transactions */

  createTransaction(
    request: CreateTransactionReq,
    metadata?: Metadata,
  ): Promise<Transaction> | Observable<Transaction> | Transaction;

  getTransactions(
    request: GetTransactionsReq,
    metadata?: Metadata,
  ): Promise<GetTransactionsRes> | Observable<GetTransactionsRes> | GetTransactionsRes;

  getTransaction(
    request: GetTransactionReq,
    metadata?: Metadata,
  ): Promise<Transaction> | Observable<Transaction> | Transaction;

  updateTransaction(
    request: UpdateTransactionReq,
    metadata?: Metadata,
  ): Promise<Transaction> | Observable<Transaction> | Transaction;

  deleteTransaction(request: DeleteTransactionReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  /** Budgets */

  createBudget(request: CreateBudgetReq, metadata?: Metadata): Promise<Budget> | Observable<Budget> | Budget;

  updateBudget(request: UpdateBudgetReq, metadata?: Metadata): Promise<Budget> | Observable<Budget> | Budget;

  deleteBudget(request: DeleteBudgetReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  /** Recurring */

  createRecurring(
    request: CreateRecurringReq,
    metadata?: Metadata,
  ): Promise<Recurinrg> | Observable<Recurinrg> | Recurinrg;

  getRecurrings(
    request: GetRecurringsReq,
    metadata?: Metadata,
  ): Promise<GetRecurringsRes> | Observable<GetRecurringsRes> | GetRecurringsRes;

  getRecurring(request: RecurringReq, metadata?: Metadata): Promise<Recurinrg> | Observable<Recurinrg> | Recurinrg;

  updateRecurring(
    request: UpdateRecurringReq,
    metadata?: Metadata,
  ): Promise<Recurinrg> | Observable<Recurinrg> | Recurinrg;

  toggleRecurring(request: RecurringReq, metadata?: Metadata): Promise<Recurinrg> | Observable<Recurinrg> | Recurinrg;

  deleteRecurring(request: RecurringReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  /** Goals */

  createGoal(request: CreateGoalReq, metadata?: Metadata): Promise<Goal> | Observable<Goal> | Goal;

  getGoals(request: GetGoalsReq, metadata?: Metadata): Promise<GetGoalsRes> | Observable<GetGoalsRes> | GetGoalsRes;

  getGoal(request: GoalReq, metadata?: Metadata): Promise<Goal> | Observable<Goal> | Goal;

  updateGoal(request: UpdateGoalReq, metadata?: Metadata): Promise<Goal> | Observable<Goal> | Goal;

  deleteGoal(request: GoalReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  contributeToGoal(
    request: CreateGoalContributionReq,
    metadata?: Metadata,
  ): Promise<Contribution> | Observable<Contribution> | Contribution;

  updateGoalContribution(
    request: UpdateGoalContributionReq,
    metadata?: Metadata,
  ): Promise<Contribution> | Observable<Contribution> | Contribution;

  deleteContribution(
    request: DeleteGoalContributionReq,
    metadata?: Metadata,
  ): Promise<Empty> | Observable<Empty> | Empty;
}

export function FinanceServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createTransaction",
      "getTransactions",
      "getTransaction",
      "updateTransaction",
      "deleteTransaction",
      "createBudget",
      "updateBudget",
      "deleteBudget",
      "createRecurring",
      "getRecurrings",
      "getRecurring",
      "updateRecurring",
      "toggleRecurring",
      "deleteRecurring",
      "createGoal",
      "getGoals",
      "getGoal",
      "updateGoal",
      "deleteGoal",
      "contributeToGoal",
      "updateGoalContribution",
      "deleteContribution",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FinanceService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FinanceService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FINANCE_SERVICE_NAME = "FinanceService";
