// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: finance/goal.proto

/* eslint-disable */
import { Transaction } from "./transaction";

export const protobufPackage = "finance";

export interface Contribution {
  id: string;
  amount: number;
  date: string;
  description?: string | undefined;
  notes?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  transaction?: Transaction | undefined;
}

export interface Goal {
  id: string;
  name: string;
  targetDate: string;
  targetAmount: number;
  priority: string;
  statsu: string;
  description?: string | undefined;
  createdAt: string;
  updatedAt: string;
  contributions: Contribution[];
  contributedAmount?: number | undefined;
}

export interface CreateGoalReq {
  name: string;
  targetDate: string;
  targetAmount: number;
  priority: string;
  description?: string | undefined;
}

export interface GetGoalsReq {
  status: string[];
  priority: string[];
  amount?: string | undefined;
  operator?: string | undefined;
}

export interface GetGoalsRes {
  goals: Goal[];
}

export interface UpdateGoalReq {
  id: string;
  name?: string | undefined;
  targetDate?: string | undefined;
  targetAmount?: number | undefined;
  description?: string | undefined;
  priority?: string | undefined;
}

export interface GoalReq {
  id: string;
}

export interface CreateGoalContributionReq {
  goalId: string;
  amount: number;
  date: string;
  description?:
    | string
    | undefined;
  /** when transaction_id  is provided, we use its date */
  transactionId?: string | undefined;
}

export interface UpdateGoalContributionReq {
  goalId: string;
  goalContributionId: string;
  amount?: number | undefined;
  date?: string | undefined;
  description?: string | undefined;
  transactionId?: string | undefined;
}

export interface DeleteGoalContributionReq {
  goalId: string;
  goalContributionId: string;
}

export const FINANCE_PACKAGE_NAME = "finance";
