// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: finance/recurring.proto

 
import { Category, Transaction } from "./transaction";

export const protobufPackage = "finance";

export interface Recurinrg {
  id: string;
  name: string;
  amount: number;
  type: string;
  frequency: string;
  startDate: string;
  endDate?: string | undefined;
  description?: string | undefined;
  notes?: string | undefined;
  merchant?: string | undefined;
  lastRunAt?: string | undefined;
  nextRunAt?: string | undefined;
  isActive: boolean;
  category: Category | undefined;
  createdAt: string;
  updatedAt: string;
  transactions: Transaction[];
  reminderEnabled: boolean;
}

export interface CreateRecurringReq {
  name: string;
  amount: number;
  frequency: string;
  type: string;
  startDate: string;
  categorySlug: string;
  endDate?: string | undefined;
  description?: string | undefined;
  merchant?: string | undefined;
  reminderEnabled?: boolean | undefined;
}

export interface UpdateRecurringReq {
  name?: string | undefined;
  amount?: number | undefined;
  frequency?: string | undefined;
  endDate?: string | undefined;
  description?: string | undefined;
  merchant?: string | undefined;
  id: string;
  reminderEnabled?: boolean | undefined;
}

export interface GetRecurringsReq {
  isActive?: boolean | undefined;
  sortBy?: string | undefined;
  type: string[];
  frequency: string[];
}

export interface GetRecurringsRes {
  recurrings: Recurinrg[];
}

/** handle get by id, delete and toggle */
export interface RecurringReq {
  id: string;
}

export interface RecurringAggregateRes {
  activeCount: number;
  pausedCount: number;
  monthlyExpense: number;
  monthlyIncome: number;
}

export const FINANCE_PACKAGE_NAME = "finance";
