// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: finance/recurring.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "finance";

export interface CreateRecurringReq {
  name: string;
  description: string;
  amount: string;
  frequency: string;
}

export interface CreateRecurringRes {
  id: string;
  name: string;
  description: string;
  amount: string;
  frequency: string;
}

export const FINANCE_PACKAGE_NAME = "finance";

export interface RecurringServiceClient {
  createRecurring(request: CreateRecurringReq, metadata?: Metadata): Observable<CreateRecurringRes>;
}

export interface RecurringServiceController {
  createRecurring(
    request: CreateRecurringReq,
    metadata?: Metadata,
  ): Promise<CreateRecurringRes> | Observable<CreateRecurringRes> | CreateRecurringRes;
}

export function RecurringServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createRecurring"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("RecurringService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("RecurringService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const RECURRING_SERVICE_NAME = "RecurringService";
