// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: finance/split.proto

 
import { PaginateResponse } from "../paginate";
import { Transaction } from "./transaction";

export const protobufPackage = "finance";

export interface SplitSettlement {
  id: string;
  paidAt: string;
  paidAmount: number;
  /** transaction here must be an income transaction */
  transaction?: Transaction | undefined;
  createdAt: string;
}

/**
 * A participant in a split.
 * When returned from GetSplit, settlements are embedded and paid/balance are populated.
 * When returned from GetSplits (list), settlements is empty and paid/balance may be omitted.
 */
export interface SplitParticipant {
  id: string;
  name: string;
  email: string;
  /** the share this participant owes */
  amount: number;
  settlements: SplitSettlement[];
  createdAt: string;
  updatedAt: string;
  /** sum of all settlements for this participant */
  paid?:
    | number
    | undefined;
  /** amount - paid (remaining owed) */
  balance?: number | undefined;
}

/**
 * A split expense.
 * participants is populated on GetSplit (single) only.
 * total_paid, total_owed, participant_count are populated on both list and single.
 */
export interface Split {
  id: string;
  name: string;
  amount: number;
  /** OPEN | PARTIALLY_SETTLED | SETTLED */
  status: string;
  /** optional linked expense transaction */
  transaction?: Transaction | undefined;
  createdAt: string;
  updatedAt: string;
  participants: SplitParticipant[];
  /** sum of all settled amounts across all participants */
  totalPaid?:
    | number
    | undefined;
  /** amount - total_paid (remaining across all participants) */
  totalOwed?: number | undefined;
}

/** Totals across all splits for the authenticated user. */
export interface GetSplitAggregateRes {
  /** sum of (amount - settled) across OPEN + PARTIALLY_SETTLED splits */
  totalOwed: number;
  /** sum of all settlements across all splits */
  totalPaid: number;
  /** number of OPEN splits */
  openCount: number;
  /** number of PARTIALLY_SETTLED splits */
  partialCount: number;
  /** number of SETTLED splits */
  settledCount: number;
  settledAmount: number;
}

export interface GetSplitsReq {
  /**
   * Filter by one or more statuses (OPEN, PARTIALLY_SETTLED, SETTLED).
   * Omit or leave empty to return all.
   */
  status: string[];
  page: number;
  limit: number;
}

export interface GetSplitsRes {
  splits: Split[];
  meta: PaginateResponse | undefined;
}

export interface SplitReq {
  id: string;
}

export interface CreateSplitReq {
  name: string;
  amount: number;
  /** optionally link to an existing expense transaction */
  transactionId?: string | undefined;
}

export interface UpdateSplitReq {
  id: string;
  name?: string | undefined;
  amount?: number | undefined;
}

export interface AddParticipantReq {
  splitId: string;
  name: string;
  email: string;
  /** the share this participant owes */
  amount: number;
}

export interface UpdateParticipantReq {
  splitId: string;
  participantId: string;
  name?: string | undefined;
  email?: string | undefined;
  amount?: number | undefined;
}

export interface ParticipantReq {
  splitId: string;
  participantId: string;
}

/**
 * Records a payment from a participant toward their share.
 * Automatically re-evaluates the split status after recording:
 *   - all participants fully paid → SETTLED
 *   - at least one payment exists → PARTIALLY_SETTLED
 *   - no payments → OPEN
 */
export interface PaySettlementReq {
  splitId: string;
  participantId: string;
  paidAmount: number;
  /** ISO 8601 date string */
  paidAt: string;
  /** the income transaction representing this payment */
  transactionId?: string | undefined;
}

export interface SettlementReq {
  splitId: string;
  settlementId: string;
}

export const FINANCE_PACKAGE_NAME = "finance";
