// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: finance/transaction.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "finance";

export interface CreateTransactionReq {
  name: string;
  description: string;
  amount: string;
  frequency: string;
}

export interface CreateTransactionRes {
  id: string;
  name: string;
  description: string;
  amount: string;
  frequency: string;
}

export const FINANCE_PACKAGE_NAME = "finance";

export interface TransactionServiceClient {
  createTransaction(request: CreateTransactionReq, metadata?: Metadata): Observable<CreateTransactionRes>;
}

export interface TransactionServiceController {
  createTransaction(
    request: CreateTransactionReq,
    metadata?: Metadata,
  ): Promise<CreateTransactionRes> | Observable<CreateTransactionRes> | CreateTransactionRes;
}

export function TransactionServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createTransaction"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TransactionService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TransactionService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TRANSACTION_SERVICE_NAME = "TransactionService";
