// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: finance/transaction.proto

/* eslint-disable */
import { PaginateResponse } from "../paginate";

export const protobufPackage = "finance";

export enum TransactionType {
  INCOME = 0,
  EXPENSE = 1,
  UNRECOGNIZED = -1,
}

export enum TransactionSource {
  MANUAL = 0,
  BANK = 1,
  RECURRING = 2,
  OCR = 3,
  SPLIT = 4,
  UNRECOGNIZED = -1,
}

export interface Empty {
}

export interface Category {
  name: string;
  slug: string;
  color: string;
  icon: string;
}

export interface Bank {
  bankId: string;
  bankName: string;
  accountNumber: string;
  accountName: string;
}

/**
 * Lightweight split summary embedded inside a Transaction response.
 * Not the same as the full Split message defined in split.proto.
 */
export interface SplitRef {
  id: string;
  name: string;
  /** string — preserves decimals */
  amount: string;
  status: string;
}

export interface GoalContribution {
  id: string;
  /** string — preserves decimals */
  amount: string;
  date: string;
  description: string;
  notes: string;
}

export interface CreateTransactionReq {
  /** string e.g. "5000.50" */
  amount: string;
  /** ISO string e.g. "2026-03-20" */
  date: string;
  type: TransactionType;
  description?: string | undefined;
  merchant?: string | undefined;
  categorySlug: string;
  source: TransactionSource;
  sourceId: string;
  sourceData?: string | undefined;
}

export interface Transaction {
  id: string;
  /** string — preserves decimals */
  amount: string;
  date: string;
  type: string;
  source: string;
  category: Category | undefined;
  createdAt: string;
  updatedAt: string;
  merchant?: string | undefined;
  sourceId?: string | undefined;
  sourceData?: string | undefined;
  description?: string | undefined;
  notes?: string | undefined;
  bankTransactionId?: string | undefined;
  bankTransactionStatus?: string | undefined;
  bank?: Bank | undefined;
  split?: SplitRef | undefined;
  goalContribution?: GoalContribution | undefined;
}

export interface GetTransactionsReq {
  startDate?: string | undefined;
  endDate?: string | undefined;
  page: number;
  limit: number;
  /** empty array = not filtered */
  categorySlug: string[];
  /** empty array = not filtered */
  type: TransactionType[];
  /** empty array = not filtered */
  source: TransactionSource[];
  sourceId?: string | undefined;
  bankTransactionId?: string | undefined;
  bankAccountId?: string | undefined;
}

export interface GetTransactionsRes {
  transactions: Transaction[];
  meta: PaginateResponse | undefined;
}

export interface GetTransactionReq {
  id: string;
}

export interface UpdateTransactionReq {
  id: string;
  amount?: string | undefined;
  date?: string | undefined;
  type?: TransactionType | undefined;
  description?: string | undefined;
  merchant?: string | undefined;
  categorySlug?: string | undefined;
  notes?: string | undefined;
}

export interface DeleteTransactionReq {
  id: string;
}

/**
 * Used exclusively for bank sync batch imports.
 * category_id is pre-resolved by the processor — no category lookup needed.
 */
export interface BankTransactionItem {
  amount: string;
  date: string;
  type: TransactionType;
  description?: string | undefined;
  categoryId: string;
  sourceId: string;
  source: TransactionSource;
  merchant?: string | undefined;
  monoBankAccountId?: string | undefined;
  aiClassified: boolean;
  narration?: string | undefined;
  bankTransactionId?:
    | string
    | undefined;
  /** JSON-stringified audit blob */
  sourceData?: string | undefined;
  categoryName: string;
}

export interface BatchCreateTransactionsReq {
  transactions: BankTransactionItem[];
}

export interface BatchCreateTransactionsRes {
  created: number;
  skipped: number;
}

/** Daily expense total for a single calendar day. */
export interface DailySpending {
  /** "YYYY-MM-DD" */
  date: string;
  /** decimal string, expense amount only */
  amount: string;
}

/** Aggregated income and expense for a single calendar month. */
export interface MonthlyFinancials {
  /** "YYYY-MM" */
  month: string;
  /** decimal string */
  income: string;
  /** decimal string */
  expense: string;
}

export interface SearchTransactionsReq {
  /** partial text — union ILIKE across description, merchant, notes, narration */
  q: string;
  /** "EXPENSE" | "INCOME" | "" (all) */
  type: string;
  /** default 20, max 50 */
  limit: number;
}

export interface SearchTransactionsRes {
  transactions: Transaction[];
}

export interface GetTransactionSummaryReq {
  /** how many months of monthly_series to return (server caps per plan) */
  months?: number | undefined;
}

export interface GetTransactionSummaryRes {
  /** all-time income - expense */
  netBalance: string;
  /** current calendar month INCOME sum */
  monthlyIncome: string;
  /** current calendar month EXPENSE sum */
  monthlyExpense: string;
  /** monthly_income - monthly_expense */
  monthlyNet: string;
  /** ((this_month_net - last_month_net) / |last_month_net|) * 100 */
  balanceChangePct: number;
  /** Mon-Sun this week (up to 7 items) */
  weeklySpending: DailySpending[];
  /** last 84 days (12 weeks x 7) */
  spendingHeatmap: DailySpending[];
  /** last N months for trend charts */
  monthlySeries: MonthlyFinancials[];
}

export const FINANCE_PACKAGE_NAME = "finance";
