/**
 * PNG chart exports rendered via headless Puppeteer (dark FinTrack theme).
 *
 * @module image.generator
 */

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

import puppeteer from 'puppeteer';

import type { SpendingTrendMonth } from '@fintrack/types/protos/finance/budget';
import type { MonthlyFinancials } from '@fintrack/types/protos/finance/transaction';
import { formatNGNCompact } from '../export.format';

const LOGO_WHITE_PATH = (() => {
  const candidates = [
    join(__dirname, '..', '..', '..', 'assets', 'logo-white.png'),
    join(__dirname, '..', '..', 'assets', 'logo-white.png'),
    join(process.cwd(), 'assets', 'logo-white.png'),
  ];
  return candidates.find(existsSync) ?? null;
})();

const LOGO_WHITE_B64: string | null = LOGO_WHITE_PATH
  ? `data:image/png;base64,${readFileSync(LOGO_WHITE_PATH).toString('base64')}`
  : null;

const BG = '#0d0d1a';
const SURFACE = '#1a1a2e';
const PRIMARY = '#7c7aff';
const GREEN = '#30d158';
const RED = '#ff453a';
const MUTED = '#6b7280';
const TEXT = '#f9fafb';

async function screenshot(
  html: string,
  width: number,
  height: number,
): Promise<Buffer> {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu'],
  });
  try {
    const page = await browser.newPage();
    await page.setViewport({ width, height, deviceScaleFactor: 2 });
    await page.setContent(html, { waitUntil: 'load' });
    const buf = await page.screenshot({ type: 'png', fullPage: false });
    return Buffer.from(buf);
  } finally {
    await browser.close();
  }
}

// ─── Spending Breakdown ───────────────────────────────────────────────────────

/**
 * @description Top-8 category horizontal bar chart for spending-breakdown exports.
 */
export async function generateSpendingBreakdownImage(
  trendData: SpendingTrendMonth[],
  periodLabel: string,
): Promise<Buffer> {
  const map = new Map<
    string,
    { name: string; color: string; amount: number }
  >();
  for (const month of trendData) {
    for (const cat of month.byCategory ?? []) {
      const existing = map.get(cat.name);
      if (existing) existing.amount += cat.amount;
      else
        map.set(cat.name, {
          name: cat.name,
          color: cat.color || PRIMARY,
          amount: cat.amount,
        });
    }
  }
  const categories = [...map.values()]
    .sort((a, b) => b.amount - a.amount)
    .slice(0, 8);
  const total = categories.reduce((s, c) => s + c.amount, 0) || 1;

  const bars = categories
    .map((cat) => {
      const pct = ((cat.amount / total) * 100).toFixed(1);
      const barW = Math.round((cat.amount / total) * 420);
      return `
        <div class="row">
          <div class="label">${cat.name}</div>
          <div class="bar-wrap"><div class="bar" style="width:${barW}px;background:${cat.color || PRIMARY}"></div></div>
          <div class="val">${formatNGNCompact(cat.amount)} <span class="pct">${pct}%</span></div>
        </div>`;
    })
    .join('');

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
<style>
* { margin:0; padding:0; box-sizing:border-box; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; }
body { background:${BG}; color:${TEXT}; width:800px; padding:40px; }
.brand { color:${PRIMARY}; font-size:18px; font-weight:700; margin-bottom:6px; }
.title { font-size:22px; font-weight:700; margin-bottom:4px; }
.sub { color:${MUTED}; font-size:13px; margin-bottom:28px; }
.row { display:flex; align-items:center; gap:12px; margin-bottom:14px; }
.label { width:130px; font-size:12px; color:${TEXT}; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; flex-shrink:0; }
.bar-wrap { flex:1; height:10px; background:${SURFACE}; border-radius:5px; overflow:hidden; }
.bar { height:10px; border-radius:5px; }
.val { width:120px; font-size:11px; font-weight:600; text-align:right; flex-shrink:0; }
.pct { color:${MUTED}; font-weight:400; }
.footer { margin-top:28px; color:${MUTED}; font-size:11px; }
</style></head><body>
${LOGO_WHITE_B64 ? `<img src="${LOGO_WHITE_B64}" style="height:40px;margin-bottom:8px;display:block">` : `<div class="brand">FinTrack</div>`}
<div class="title">Spending Breakdown</div>
<div class="sub">${periodLabel}</div>
${bars}
<div class="footer">Generated by FinTrack · ${new Date().toLocaleDateString('en-GB')}</div>
</body></html>`;

  const h = 140 + categories.length * 28 + 80;
  return screenshot(html, 800, Math.max(400, h));
}

// ─── Net Worth ────────────────────────────────────────────────────────────────

/**
 * @description Net worth statement with cumulative balance area chart.
 */
export async function generateNetWorthImage(
  series: MonthlyFinancials[],
  netBalance: string,
): Promise<Buffer> {
  const sorted = [...series].sort((a, b) => a.month.localeCompare(b.month));
  let running = 0;
  const points = sorted.map((m) => {
    running += parseFloat(m.income) - parseFloat(m.expense);
    return { label: m.month, value: parseFloat(running.toFixed(2)) };
  });

  const values = points.map((p) => p.value);
  const min = Math.min(0, ...values);
  const max = Math.max(0, ...values);
  const range = max - min || 1;
  const W = 680;
  const H = 200;
  const PL = 60;
  const PR = 20;
  const PT = 10;
  const PB = 30;
  const gW = W - PL - PR;
  const gH = H - PT - PB;
  const toX = (i: number) => PL + (i / Math.max(points.length - 1, 1)) * gW;
  const toY = (v: number) => PT + gH - ((v - min) / range) * gH;

  const pathD = points
    .map(
      (p, i) =>
        `${i === 0 ? 'M' : 'L'} ${toX(i).toFixed(1)} ${toY(p.value).toFixed(1)}`,
    )
    .join(' ');
  const areaD = `${pathD} L ${toX(points.length - 1).toFixed(1)} ${toY(0).toFixed(1)} L ${toX(0).toFixed(1)} ${toY(0).toFixed(1)} Z`;

  const isGrowing = (values[values.length - 1] ?? 0) >= (values[0] ?? 0);
  const lineColor = isGrowing ? GREEN : RED;
  const balance = parseFloat(netBalance);

  const step = Math.max(1, Math.floor(points.length / 5));
  const xLabels = points
    .filter((_, i) => i % step === 0 || i === points.length - 1)
    .map((p) => {
      const i = points.indexOf(p);
      return `<text x="${toX(i).toFixed(1)}" y="${H - 4}" fill="${MUTED}" font-size="9" text-anchor="middle">${p.label}</text>`;
    })
    .join('');

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
<style>
* { margin:0; padding:0; box-sizing:border-box; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; }
body { background:${BG}; color:${TEXT}; width:800px; padding:40px; }
.brand { color:${PRIMARY}; font-size:18px; font-weight:700; margin-bottom:6px; }
.title { font-size:22px; font-weight:700; margin-bottom:4px; }
.sub { color:${MUTED}; font-size:13px; margin-bottom:24px; }
.metrics { display:flex; gap:48px; margin-bottom:28px; }
.m-label { color:${MUTED}; font-size:11px; margin-bottom:4px; }
.m-val { font-size:20px; font-weight:700; }
.chart { background:${SURFACE}; border-radius:12px; padding:16px; }
svg { display:block; }
.footer { margin-top:20px; color:${MUTED}; font-size:11px; }
</style></head><body>
${LOGO_WHITE_B64 ? `<img src="${LOGO_WHITE_B64}" style="height:40px;margin-bottom:8px;display:block">` : `<div class="brand">FinTrack</div>`}
<div class="title">Net Worth Statement</div>
<div class="sub">Generated ${new Date().toLocaleDateString('en-GB')}</div>
<div class="metrics">
  <div><div class="m-label">Net Balance</div><div class="m-val" style="color:${balance >= 0 ? GREEN : RED}">${formatNGNCompact(balance)}</div></div>
  <div><div class="m-label">Trend</div><div class="m-val" style="color:${lineColor}">${isGrowing ? '↑ Growing' : '↓ Declining'}</div></div>
</div>
<div class="chart">
<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="${lineColor}" stop-opacity="0.3"/>
      <stop offset="100%" stop-color="${lineColor}" stop-opacity="0"/>
    </linearGradient>
  </defs>
  <line x1="${PL}" y1="${toY(0).toFixed(1)}" x2="${W - PR}" y2="${toY(0).toFixed(1)}" stroke="${MUTED}" stroke-width="0.5" stroke-dasharray="3,3"/>
  <path d="${areaD}" fill="url(#g)"/>
  <path d="${pathD}" fill="none" stroke="${lineColor}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"/>
  ${xLabels}
</svg>
</div>
<div class="footer">Generated by FinTrack · ${new Date().toLocaleDateString('en-GB')}</div>
</body></html>`;

  return screenshot(html, 800, 520);
}
