// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: ai/ai.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "ai";

export interface MonoTransaction {
  id: string;
  narration: string;
  category: string;
}

export interface UserCategory {
  id: string;
  slug: string;
  tags: string[];
  name: string;
}

export interface ClassifyTransactionsReq {
  transactions: MonoTransaction[];
  categories: UserCategory[];
}

export interface ClassifyTransactionsUnit {
  transactionId: string;
  categoryId: string;
  categorySlug: string;
}

export interface ClassifyTransactionsRes {
  classifications: ClassifyTransactionsUnit[];
}

export const AI_PACKAGE_NAME = "ai";

export interface AiServiceClient {
  classifyTransactions(request: ClassifyTransactionsReq, metadata?: Metadata): Observable<ClassifyTransactionsRes>;
}

export interface AiServiceController {
  classifyTransactions(
    request: ClassifyTransactionsReq,
    metadata?: Metadata,
  ): Promise<ClassifyTransactionsRes> | Observable<ClassifyTransactionsRes> | ClassifyTransactionsRes;
}

export function AiServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["classifyTransactions"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AiService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AiService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AI_SERVICE_NAME = "AiService";
