// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: ai/ai.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "ai";

export interface GenerateTextReq {
  prompt: string;
}

export interface GenerateTextRes {
  text: string;
}

export const AI_PACKAGE_NAME = "ai";

export interface AiServiceClient {
  generateText(request: GenerateTextReq, metadata?: Metadata): Observable<GenerateTextRes>;
}

export interface AiServiceController {
  generateText(
    request: GenerateTextReq,
    metadata?: Metadata,
  ): Promise<GenerateTextRes> | Observable<GenerateTextRes> | GenerateTextRes;
}

export function AiServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["generateText"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AiService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AiService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AI_SERVICE_NAME = "AiService";
