import { ModelId, ModelProviderConfig } from '../interfaces/ai';

export const DEFAULT_EMB_MAX_TOKENS = 8191;

export const EXTRACTION_TIMEOUT_MS = 45_000;

export const MODEL_CONFIGS: Record<ModelId, ModelProviderConfig> = {
  // ─── OpenAI chat / reasoning ──────────────────────────────────────────────
  'openai:gpt-4o': {
    model: 'gpt-4o',
    provider: 'openai',
    cache: true,
    maxTokens: 4096,
    temperature: 0.7,
    timeout: 30_000,
    streaming: true,
  },
  'openai:gpt-4-turbo': {
    model: 'gpt-4-turbo',
    provider: 'openai',
    cache: true,
    maxTokens: 4096,
    temperature: 0.7,
    timeout: 30_000,
    streaming: true,
  },
  'openai:gpt-3.5-turbo': {
    model: 'gpt-3.5-turbo',
    provider: 'openai',
    cache: true,
    maxTokens: 2048,
    temperature: 0.7,
    timeout: 20_000,
    streaming: true,
  },
  'openai:gpt-5': {
    model: 'gpt-5',
    provider: 'openai',
    cache: true,
    maxTokens: 8192,
    temperature: 0.7,
    timeout: 30_000,
    streaming: true,
  },
  'openai:gpt-5.4': {
    model: 'gpt-5.4',
    provider: 'openai',
    cache: true,
    maxTokens: 8192,
    temperature: 0.7,
    timeout: 30_000,
    streaming: true,
  },
  'openai:gpt-5.4-mini': {
    model: 'gpt-5.4-mini',
    provider: 'openai',
    cache: true,
    maxTokens: 4096,
    temperature: 0.7,
    timeout: 15_000,
    streaming: true,
  },
  'openai:gpt-5.4-nano': {
    model: 'gpt-5.4-nano',
    provider: 'openai',
    cache: true,
    maxTokens: 2048,
    temperature: 0.7,
    timeout: 10_000,
    streaming: false,
  },
  'openai:gpt-5-mini': {
    model: 'gpt-5-mini',
    provider: 'openai',
    cache: true,
    maxTokens: 4096,
    temperature: 0.7,
    timeout: 15_000,
    streaming: true,
  },
  'openai:o3-mini': {
    model: 'o3-mini',
    provider: 'openai',
    cache: true,
    maxTokens: 4096,
    temperature: 0.7,
    timeout: 10_000,
    streaming: false,
  },
  'openai:o4-mini': {
    model: 'o4-mini',
    provider: 'openai',
    cache: true,
    maxTokens: 4096,
    temperature: 0.7,
    timeout: 15_000,
    streaming: false,
  },

  // ─── OpenAI embeddings ────────────────────────────────────────────────────
  'openai:text-embedding-3-small': {
    model: 'text-embedding-3-small',
    provider: 'openai',
    cache: true,
    maxTokens: DEFAULT_EMB_MAX_TOKENS,
    timeout: 10_000,
    streaming: false,
    dimensions: 1536,
  },
  'openai:text-embedding-3-large': {
    model: 'text-embedding-3-large',
    provider: 'openai',
    cache: true,
    maxTokens: DEFAULT_EMB_MAX_TOKENS,
    timeout: 15_000,
    streaming: false,
    dimensions: 1536,
  },
  'openai:text-embedding-ada-002': {
    model: 'text-embedding-ada-002',
    provider: 'openai',
    cache: true,
    maxTokens: DEFAULT_EMB_MAX_TOKENS,
    timeout: 10_000,
    streaming: false,
    dimensions: 1536,
  },

  // ─── Anthropic chat / reasoning ───────────────────────────────────────────
  'anthropic:claude-3-5-sonnet': {
    model: 'claude-3-5-sonnet-20241022',
    provider: 'anthropic',
    cache: true,
    maxTokens: 4096,
    temperature: 0.7,
    timeout: 30_000,
    streaming: true,
  },
  'anthropic:claude-3-opus': {
    model: 'claude-3-opus-20240229',
    provider: 'anthropic',
    cache: true,
    maxTokens: 4096,
    temperature: 0.5,
    timeout: 45_000,
    streaming: true,
  },
  'anthropic:claude-sonnet-4.6': {
    model: 'claude-sonnet-4-6-20250514',
    provider: 'anthropic',
    cache: true,
    maxTokens: 8192,
    temperature: 0.7,
    timeout: 30_000,
    streaming: true,
  },
  'anthropic:claude-opus-4.6': {
    model: 'claude-opus-4-6-20250514',
    provider: 'anthropic',
    cache: true,
    maxTokens: 8192,
    temperature: 0.5,
    timeout: 45_000,
    streaming: true,
  },

  // ─── Google chat / reasoning ──────────────────────────────────────────────
  'google:gemini-2.5-pro': {
    model: 'gemini-2.5-pro',
    provider: 'google',
    cache: true,
    maxTokens: 8192,
    temperature: 0.7,
    timeout: 60_000,
    streaming: true,
  },
  'google:gemini-2.5-flash': {
    model: 'gemini-2.5-flash',
    provider: 'google',
    cache: true,
    maxTokens: 4096,
    temperature: 0.7,
    timeout: 30_000,
    streaming: true,
  },

  // ─── Google embeddings ────────────────────────────────────────────────────
  'google:gemini-embedding-2': {
    model: 'gemini-embedding-2',
    provider: 'google',
    cache: true,
    maxTokens: DEFAULT_EMB_MAX_TOKENS,
    timeout: 10_000,
    streaming: false,
    dimensions: 1536,
  },
};
