//!! TOKEN_NOTIFICATION_QUEUE
export const TOKEN_NOTIFICATION_QUEUE = 'TOKEN_NOTIFICATION_QUEUE';
//? TOKEN NOTIFICATION JOBS
export const EMAIL_VERIFICATION_JOB = 'EMAIL_VERIFICATION';
export const WELCOME_EMAIL_JOB = 'WELCOME_EMAIL_JOB';
export const PASSWORD_CHANGE_JOB = 'PASSWORD_CHANGE';
export const FORGOT_PASSWORD_EMAIL_JOB = 'FORGOT_PASSWORD_EMAIL';
export const EMAIL_CHANGE_JOB = 'EMAIL_CHANGE';
export const EMAIL_CHANGED_JOB = 'EMAIL_CHANGED';

//!! ACCOUNT CLEANUP QUEUE
export const ACCOUNT_CLEANUP_QUEUE = 'ACCOUNT_CLEANUP_QUEUE';
//? ACCOUNT CLEANUP JOBS
export const PURGE_SCHEDULED_DELETIONS_JOB = 'PURGE_SCHEDULED_DELETIONS';
export const CANCEL_STRIPE_SUBSCRIPTION_JOB = 'CANCEL_STRIPE_SUBSCRIPTION';
export const ACCOUNT_DELETION_EMAIL_JOB = 'ACCOUNT_DELETION_EMAIL';

//!! PAYMENT NOTIFICATION QUEUE
export const PAYMENT_QUEUE = 'PAYMENT_QUEUE';
//? PAYMENT NOTIFICATION JOBS
export const CREATE_CHECKOUT_SESSION_JOB = 'CREATE_CHECKOUT_SESSION';
export const INVOICE_PAID_JOB = 'INVOICE_PAID';
export const INVOICE_PAYMENT_FAILED_JOB = 'INVOICE_PAYMENT_FAILED';
export const SUBSCRIPTION_DEACTIVATED_JOB = 'SUBSCRIPTION_DEACTIVATED';
export const SUBSCRIPTION_ACTIVATED_JOB = 'SUBSCRIPTION_ACTIVATED';
export const SUBSCRIPTION_DELETED_JOB = 'SUBSCRIPTION_DELETED';

//!! USAGE TRACKING QUEUE
export const USAGE_TRACKING_QUEUE = 'USAGE_TRACKING_QUEUE';
//? USAGE TRACKING JOBS
export const PURGE_USAGE_TRACKING_JOB = 'PURGE_USAGE_TRACKING';
