export const TOKEN_NOTIFICATION_QUEUE = 'TOKEN_NOTIFICATION_QUEUE';

export const EMAIL_VERIFICATION_JOB = 'EMAIL_VERIFICATION';

export const WELCOME_EMAIL_JOB = 'WELCOME_EMAIL_JOB';
export const PASSWORD_CHANGE_JOB = 'PASSWORD_CHANGE';
export const FORGOT_PASSWORD_EMAIL_JOB = 'FORGOT_PASSWORD_EMAIL';
