export const TOKEN_NOTIFICATION_QUEUE = 'TOKEN_NOTIFICATION_QUEUE';

export const EMAIL_VERIFICATION_JOB = 'EMAIL_VERIFICATION';

export const WELCOME_EMAIL_JOB = 'WELCOME_EMAIL_JOB';
export const PASSWORD_CHANGE_JOB = 'PASSWORD_CHANGE';
export const FORGOT_PASSWORD_EMAIL_JOB = 'FORGOT_PASSWORD_EMAIL';
export const EMAIL_CHANGE_JOB = 'EMAIL_CHANGE';
export const EMAIL_CHANGED_JOB = 'EMAIL_CHANGED';

export const ACCOUNT_CLEANUP_QUEUE = 'ACCOUNT_CLEANUP_QUEUE';
export const PURGE_SCHEDULED_DELETIONS_JOB = 'PURGE_SCHEDULED_DELETIONS';
export const CANCEL_STRIPE_SUBSCRIPTION_JOB = 'CANCEL_STRIPE_SUBSCRIPTION';
export const ACCOUNT_DELETION_EMAIL_JOB = 'ACCOUNT_DELETION_EMAIL';
