// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: auth/auth.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

/** ------- REUSABLE EMPTY INTERFACE ---------- // */
export interface Empty {
}

export interface User {
  id: string;
  email: string;
  avatar?: string | undefined;
  firstName: string;
  lastName: string;
}

export interface RegisterReq {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
}

export interface RegisterRes {
  user: User | undefined;
  emailToken: string;
}

export interface VerifyEmailReq {
  otp: string;
  deviceId: string;
  userAgent?: string | undefined;
  ipAddress?: string | undefined;
  location?: string | undefined;
}

export interface VerifyEmailRes {
  user: User | undefined;
  accessToken: string;
  refreshToken: string;
}

export interface ResendVerifyEmailTokenReq {
  email: string;
}

export interface ResendVerifyEmailTokenRes {
  user: User | undefined;
  emailToken: string;
}

export interface LoginReq {
  email: string;
  password: string;
  deviceId: string;
  userAgent?: string | undefined;
  ipAddress?: string | undefined;
  location?: string | undefined;
}

export interface LoginRes {
  user: User | undefined;
  accessToken: string;
  refreshToken: string;
}

export interface ForgotPasswordReq {
  email: string;
}

export interface ForgotPasswordRes {
  email: string;
}

export interface ResendForgotPasswordTokenReq {
  email: string;
}

export interface ResendForgotPasswordTokenRes {
  email: string;
}

export interface VerifyPasswordTokenReq {
  email: string;
  otp: string;
}

export interface VerifyPasswordTokenRes {
  passwordToken: string;
}

export interface ResetPasswordReq {
  newPassword: string;
}

export interface ValidateTokenRes {
  id: string;
  email: string;
  avatar: string;
  firstName: string;
  lastName: string;
}

export interface RefreshTokenRes {
  accessToken: string;
  refreshToken: string;
}

export interface LoginwithGoggleReq {
  idToken: string;
  deviceId: string;
  userAgent?: string | undefined;
  ipAddress?: string | undefined;
  location?: string | undefined;
}

export interface InitiateTwoFactorSetupRes {
  /** base32 — for manual entry in authenticator app -> Unencrypted at this stage */
  secret: string;
  /** full otpauth://totp/... URI — render as QR code */
  otpauthUri: string;
}

export interface ConfirmTwoFactorSetupReq {
  /** 6-digit code from authenticator app — proves setup worked */
  code: string;
}

export interface ConfirmTwoFactorSetupRes {
  /** 10 plain codes — shown ONCE, never stored plain */
  backupCodes: string[];
}

export interface DisableTwoFactorReq {
  /** requires current TOTP code — prevents unauthorised disable */
  code: string;
}

export interface VerifyTwoFactorReq {
  /** short-lived JWT returned by Login when 2FA required */
  twoFactorToken: string;
  /** 6-digit TOTP or 8-char backup code */
  code: string;
  deviceId: string;
  userAgent?: string | undefined;
  ipAddress?: string | undefined;
  location?: string | undefined;
}

export interface ChangePasswordReq {
  /** current password — verifies ownership before change */
  currentPassword: string;
  newPassword: string;
}

export interface ChangeEmailReq {
  /** the new email address to change to */
  newEmail: string;
  /** current password — verifies ownership before change */
  currentPassword: string;
}

export interface InitiateEmailChangeRes {
  /** the address the OTP was sent to */
  newEmail: string;
}

export interface VerifyEmailChangeReq {
  /** 6-digit code sent to the new email address */
  otp: string;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  register(request: RegisterReq, metadata?: Metadata): Observable<RegisterRes>;

  verifyEmail(request: VerifyEmailReq, metadata?: Metadata): Observable<VerifyEmailRes>;

  resendVerifyEmailToken(
    request: ResendVerifyEmailTokenReq,
    metadata?: Metadata,
  ): Observable<ResendVerifyEmailTokenRes>;

  login(request: LoginReq, metadata?: Metadata): Observable<LoginRes>;

  forgotPassword(request: ForgotPasswordReq, metadata?: Metadata): Observable<ForgotPasswordRes>;

  resendForgotPasswordToken(
    request: ResendForgotPasswordTokenReq,
    metadata?: Metadata,
  ): Observable<ResendForgotPasswordTokenRes>;

  verifyPasswordToken(request: VerifyPasswordTokenReq, metadata?: Metadata): Observable<VerifyPasswordTokenRes>;

  resetPassword(request: ResetPasswordReq, metadata?: Metadata): Observable<Empty>;

  validateToken(request: Empty, metadata?: Metadata): Observable<ValidateTokenRes>;

  refreshToken(request: Empty, metadata?: Metadata): Observable<RefreshTokenRes>;

  loginWithGoogle(request: LoginwithGoggleReq, metadata?: Metadata): Observable<LoginRes>;

  initiateTwoFactorSetup(request: Empty, metadata?: Metadata): Observable<InitiateTwoFactorSetupRes>;

  confirmTwoFactorSetup(request: ConfirmTwoFactorSetupReq, metadata?: Metadata): Observable<ConfirmTwoFactorSetupRes>;

  disableTwoFactor(request: DisableTwoFactorReq, metadata?: Metadata): Observable<Empty>;

  verifyTwoFactor(request: VerifyTwoFactorReq, metadata?: Metadata): Observable<LoginRes>;

  changePassword(request: ChangePasswordReq, metadata?: Metadata): Observable<Empty>;

  initiateEmailChange(request: ChangeEmailReq, metadata?: Metadata): Observable<InitiateEmailChangeRes>;

  verifyEmailChange(request: VerifyEmailChangeReq, metadata?: Metadata): Observable<Empty>;
}

export interface AuthServiceController {
  register(request: RegisterReq, metadata?: Metadata): Promise<RegisterRes> | Observable<RegisterRes> | RegisterRes;

  verifyEmail(
    request: VerifyEmailReq,
    metadata?: Metadata,
  ): Promise<VerifyEmailRes> | Observable<VerifyEmailRes> | VerifyEmailRes;

  resendVerifyEmailToken(
    request: ResendVerifyEmailTokenReq,
    metadata?: Metadata,
  ): Promise<ResendVerifyEmailTokenRes> | Observable<ResendVerifyEmailTokenRes> | ResendVerifyEmailTokenRes;

  login(request: LoginReq, metadata?: Metadata): Promise<LoginRes> | Observable<LoginRes> | LoginRes;

  forgotPassword(
    request: ForgotPasswordReq,
    metadata?: Metadata,
  ): Promise<ForgotPasswordRes> | Observable<ForgotPasswordRes> | ForgotPasswordRes;

  resendForgotPasswordToken(
    request: ResendForgotPasswordTokenReq,
    metadata?: Metadata,
  ): Promise<ResendForgotPasswordTokenRes> | Observable<ResendForgotPasswordTokenRes> | ResendForgotPasswordTokenRes;

  verifyPasswordToken(
    request: VerifyPasswordTokenReq,
    metadata?: Metadata,
  ): Promise<VerifyPasswordTokenRes> | Observable<VerifyPasswordTokenRes> | VerifyPasswordTokenRes;

  resetPassword(request: ResetPasswordReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  validateToken(
    request: Empty,
    metadata?: Metadata,
  ): Promise<ValidateTokenRes> | Observable<ValidateTokenRes> | ValidateTokenRes;

  refreshToken(
    request: Empty,
    metadata?: Metadata,
  ): Promise<RefreshTokenRes> | Observable<RefreshTokenRes> | RefreshTokenRes;

  loginWithGoogle(
    request: LoginwithGoggleReq,
    metadata?: Metadata,
  ): Promise<LoginRes> | Observable<LoginRes> | LoginRes;

  initiateTwoFactorSetup(
    request: Empty,
    metadata?: Metadata,
  ): Promise<InitiateTwoFactorSetupRes> | Observable<InitiateTwoFactorSetupRes> | InitiateTwoFactorSetupRes;

  confirmTwoFactorSetup(
    request: ConfirmTwoFactorSetupReq,
    metadata?: Metadata,
  ): Promise<ConfirmTwoFactorSetupRes> | Observable<ConfirmTwoFactorSetupRes> | ConfirmTwoFactorSetupRes;

  disableTwoFactor(request: DisableTwoFactorReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  verifyTwoFactor(
    request: VerifyTwoFactorReq,
    metadata?: Metadata,
  ): Promise<LoginRes> | Observable<LoginRes> | LoginRes;

  changePassword(request: ChangePasswordReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  initiateEmailChange(
    request: ChangeEmailReq,
    metadata?: Metadata,
  ): Promise<InitiateEmailChangeRes> | Observable<InitiateEmailChangeRes> | InitiateEmailChangeRes;

  verifyEmailChange(request: VerifyEmailChangeReq, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "register",
      "verifyEmail",
      "resendVerifyEmailToken",
      "login",
      "forgotPassword",
      "resendForgotPasswordToken",
      "verifyPasswordToken",
      "resetPassword",
      "validateToken",
      "refreshToken",
      "loginWithGoogle",
      "initiateTwoFactorSetup",
      "confirmTwoFactorSetup",
      "disableTwoFactor",
      "verifyTwoFactor",
      "changePassword",
      "initiateEmailChange",
      "verifyEmailChange",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
