// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: auth/auth.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface AuthReq {
  token: string;
}

export interface AuthRes {
  id: string;
  status: string;
}

export interface LoginReq {
  userName: string;
  password: string;
}

export interface LoginRes {
  token: string;
  id: string;
}

export interface RegisterRes {
  id: string;
  userName: string;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  login(request: LoginReq, metadata?: Metadata): Observable<LoginRes>;

  register(request: LoginReq, metadata?: Metadata): Observable<RegisterRes>;

  auth(request: AuthReq, metadata?: Metadata): Observable<AuthRes>;
}

export interface AuthServiceController {
  login(request: LoginReq, metadata?: Metadata): Promise<LoginRes> | Observable<LoginRes> | LoginRes;

  register(request: LoginReq, metadata?: Metadata): Promise<RegisterRes> | Observable<RegisterRes> | RegisterRes;

  auth(request: AuthReq, metadata?: Metadata): Promise<AuthRes> | Observable<AuthRes> | AuthRes;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["login", "register", "auth"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
