import { PRO_PLAN_KEY, TRIAL_KEY } from '../constants/payment.constants';

//* Paystack Chaneels
export type PaysatckChannels =
  | 'card'
  | 'bank'
  | 'apple_pay'
  | 'ussd'
  | 'qr'
  | 'mobile_money'
  | 'bank_transfer'
  | 'eft'
  | 'capitec_pay'
  | 'payattitude';

//* Paystack response warpper
export interface PaystackResponse<T = undefined> {
  /** Whether the request was successful */
  status: boolean;
  /** Human-readable description of the result */
  message: string;
  /** Response payload; absent on error responses */
  data?: T;
}

//* Initialize transaction
export interface InitializePaystackTranactionPayload {
  /** Customer email address */
  email: string;
  /** Amount to charge in kobo (e.g. 50000 = ₦500) */
  amountKobo: number;
  /** Unique transaction reference; auto-generated by Paystack if omitted */
  reference?: string;
  /** URL Paystack redirects to after payment */
  callbackUrl?: string;
  /** Payment channels to show the customer */
  channels?: PaysatckChannels[];
  /** Arbitrary key-value data attached to the transaction */
  metadata?: Record<string, unknown>;
  /** Plan code for direct pro upgrade */
  plan?: string;
}
export interface InitializePaystackTransactionResponse {
  /** Hosted payment page URL — redirect the user here */
  authorization_url: string;
  /** Short-lived code used with Paystack Inline JS */
  access_code: string;
  /** Transaction reference to track this payment */
  reference: string;
}

//* Verify Transdaction
export interface VerifyTransactionPayload {
  /** Transaction reference to verify */
  reference: string;
}
export interface VerifyTransactionResponse {
  /** Paystack internal transaction ID */
  id: number;
  /** Terminal status of the transaction */
  status: 'success' | 'failed';
  /** Unique transaction reference */
  reference: string;
  /** Amount charged in kobo */
  amount: number;
  /** ISO 8601 timestamp when payment was completed */
  paid_at: string;
  /** ISO 8601 timestamp when the transaction was created */
  created_at: string;
  /** Payment channel used */
  channel: PaysatckChannels;
  /** Transaction currency */
  currency: 'NGN';
  /** Customer IP address at checkout */
  ip_address: string;
  /** Arbitrary metadata attached at initialization */
  metadata: Record<string, any>;
  /** Paystack processing fee in kobo */
  fees: number;
  /** Fee split details; null if no split configured */
  fees_split: any;
  /** Card authorization details — store `authorization_code` for recurring charges */
  authorization: {
    /** Reusable token for future charges — store encrypted */
    authorization_code: string;
    /** First 6 digits of the card (BIN) */
    bin: string;
    /** Last 4 digits of the card */
    last4: string;
    /** Card expiry month (MM) */
    exp_month: string;
    /** Card expiry year (YYYY) */
    exp_year: string;
    /** Channel the card was charged through */
    channel: PaysatckChannels;
    /** Card scheme and type e.g. "visa debit" */
    card_type: 'visa ' | 'verve' | 'master';
    /** Issuing bank name */
    bank: string;
    /** ISO 3166-1 alpha-2 country code of the issuing bank */
    country_code: 'NG';
    /** Card brand */
    brand: 'visa ' | 'verve' | 'master';
    /** Whether this authorization can be used for future charges */
    reusable: boolean;
    /** Paystack authorization signature */
    signature: string;
    /** Account name on the card; null if unavailable */
    account_name: any;
  };
  /** Customer details */
  customer: {
    /** Paystack internal customer ID */
    id: number;
    /** Customer first name; null if not provided */
    first_name: any;
    /** Customer last name; null if not provided */
    last_name: any;
    /** Customer email address */
    email: string;
    /** Paystack customer code e.g. CUS_xxx */
    customer_code: string;
    /** Customer phone number; null if not provided */
    phone: any;
    /** Arbitrary metadata stored on the customer */
    metadata: Record<string, any>;
    /** Paystack risk classification for the customer */
    risk_action: any;
    /** E.164 formatted phone; null if not provided */
    international_format_phone: any;
  };
}

//* Refund User
export interface CreateRefundPayload {
  /** Transaction reference or id */
  transaction: string;
  /** Amount to refund in kobo; omit to refund the full transaction amount */
  amount?: number;
  /** Currency of the refund; defaults to transaction currency */
  currency?: string;
  /** Note shown to the customer */
  customer_note?: string;
  /** Internal note for merchant records */
  merchant_note?: string;
}
export interface CreateRefundResponse {
  /** Paystack internal refund ID */
  id: number;
  /** Current processing state of the refund */
  status: 'pending' | 'processing' | 'processed' | 'failed';
  /** Original transaction being refunded */
  transaction: {
    /** Paystack internal transaction ID */
    id: number;
    /** Unique transaction reference */
    reference: string;
    /** Original charge amount in kobo */
    amount: number;
    /** ISO 8601 timestamp when the transaction was paid */
    paid_at: string;
    /** Payment channel of the original transaction */
    channel: PaysatckChannels;
    /** Currency of the original transaction */
    currency: string;
    /** Card authorization details from the original transaction */
    authorization: {
      /** Card expiry month; null if unavailable */
      exp_month: string | null;
      /** Card expiry year; null if unavailable */
      exp_year: string | null;
      /** Account name on the card; null if unavailable */
      account_name: string | null;
    };
    /** Customer details from the original transaction */
    customer: {
      /** E.164 formatted phone; null if not provided */
      international_format_phone: string | null;
    };
  };
  /** Paystack integration ID */
  integration: number;
  /** Amount already deducted from settlement in kobo */
  deducted_amount: number;
  /** Channel through which the refund will be processed; null if not yet determined */
  channel: string | null;
  /** Internal merchant-facing note */
  merchant_note: string;
  /** Customer-facing note */
  customer_note: string;
  /** Email of the merchant user who initiated the refund */
  refunded_by: string;
  /** ISO 8601 timestamp when the refund is expected to be completed */
  expected_at: string;
  /** Refund currency */
  currency: string;
  /** Environment: "live" or "test" */
  domain: string;
  /** Amount refunded in kobo */
  amount: number;
  /** Whether the full transaction amount was refunded */
  fully_deducted: boolean;
  /** ISO 8601 timestamp when the refund record was created */
  createdAt: string;
  /** ISO 8601 timestamp when the refund record was last updated */
  updatedAt: string;
}

//* Create Subscription
export interface CreateSubscriptionPayload {
  /** Customer email address or Paystack customer code (CUS_xxx) */
  customer: string;
  /** Paystack plan code (PLN_xxx) */
  plan: string;
  /** Authorization code to charge; uses the customer's most recent card if omitted */
  authorization?: string;
  /** ISO 8601 date for the first charge — set 2 months out for the free trial */
  start_date?: string;
}
export interface CreateSubscriptionResponse {
  /** Paystack internal subscription ID */
  id: number;
  /** Unique subscription code (SUB_xxx) — store for future API calls */
  subscription_code: string;
  /** Token required for /subscription/disable and /enable — encrypt at rest */
  email_token: string;
  /** Current subscription status */
  status: 'active' | 'non-renewing' | 'attention' | 'completed' | 'cancelled';
  /** Recurring charge amount in kobo */
  amount: number;
  /** Number of times the subscription has been charged */
  quantity: number;
  /** Unix timestamp of the first charge date */
  start: number;
  /** Environment: "live" or "test" */
  domain: string;
  /** Paystack integration ID */
  integration: number;
  /** Paystack internal customer ID */
  customer: number;
  /** Paystack internal plan ID */
  plan: number;
  /** Card authorization used for this subscription */
  authorization: {
    /** Reusable card token — encrypt at rest */
    authorization_code: string;
    /** First 6 digits of the card (BIN) */
    bin: string;
    /** Last 4 digits of the card */
    last4: string;
    /** Card expiry month (MM) */
    exp_month: string;
    /** Card expiry year (YYYY) */
    exp_year: string;
    /** Payment channel */
    channel: PaysatckChannels;
    /** Card scheme and type */
    card_type: string;
    /** Issuing bank name */
    bank: string;
    /** ISO 3166-1 alpha-2 country code of the issuing bank */
    country_code: string;
    /** Card brand */
    brand: string;
    /** Whether this authorization can be reused for future charges */
    reusable: boolean;
    /** Paystack authorization signature */
    signature: string;
    /** Account name on the card; null if unavailable */
    account_name: string | null;
  };
  /** ISO 8601 timestamp when the subscription was created */
  createdAt: string;
  /** ISO 8601 timestamp when the subscription was last updated */
  updatedAt: string;
}

//* Get Subscription Manage Link
export interface GetSubscriptionManageLinkPayload {
  /** Subscription code (SUB_xxx) */
  code: string;
}
export interface GetSubscriptionManageLinkResponse {
  /** Hosted Paystack URL for the customer to update their card or cancel */
  link: string;
}

//* Fetch Subscription (GET /subscription/:code)
export interface FetchSubscriptionResponse {
  /** Subscription code (SUB_xxx) */
  subscription_code: string;
  /** Email token required for disable/enable operations */
  email_token: string;
  /** Subscription status e.g. "active", "non-renewing", "cancelled" */
  status: string;
  /** Recurring amount in kobo */
  amount: number;
  /** ISO 8601 date of the next scheduled charge */
  next_payment_date: string | null;
  /** Cron expression for the billing schedule */
  cron_expression: string;
  /** Card authorization backing this subscription */
  authorization: PaystackWebhookAuthorization;
  /** Customer who owns the subscription */
  customer: PaystackWebhookCustomer;
  /** Plan details */
  plan: PaystackWebhookPlan;
}

//* Enable Subscription
export interface EnableSubscriptionPayload {
  /** Subscription code (SUB_xxx) */
  code: string;
  /** Email token from the create subscription response — decrypt before use */
  token: string;
}
export type EnableSubscriptionResponse = Record<never, never>;

//* Disable Subscription
export interface DisableSubscriptionPayload {
  /** Subscription code (SUB_xxx) */
  code: string;
  /** Email token from the create subscription response — decrypt before use */
  token: string;
}
export type DisableSubscriptionResponse = Record<never, never>;

export interface PaymmentMetadata {
  userId: string;
  purpose: typeof TRIAL_KEY | typeof PRO_PLAN_KEY;
}

// ---------------------------------------------------------------------------
// Paystack Webhook Events
// ---------------------------------------------------------------------------

export type PaystackEventType =
  | 'charge.success'
  | 'invoice.create'
  | 'invoice.update'
  | 'invoice.payment_failed'
  | 'subscription.create'
  | 'subscription.disable'
  | 'subscription.not_renew'
  | 'subscription.expiring_cards';

//* Generic envelope — every Paystack webhook has this top-level shape
export interface PaystackWebhookEvent<T = unknown> {
  /** Paystack event type */
  event: PaystackEventType;
  /** Event-specific payload */
  data: T;
}

//* Shared sub-shapes reused across multiple event payloads

export interface PaystackWebhookAuthorization {
  /** Reusable card token — store encrypted */
  authorization_code: string;
  /** First 6 digits of the card */
  bin: string;
  /** Last 4 digits of the card */
  last4: string;
  /** Card expiry month (MM) */
  exp_month: string;
  /** Card expiry year (YYYY) */
  exp_year: string;
  /** Payment channel; absent on some older events */
  channel?: PaysatckChannels;
  /** Card scheme and type e.g. "visa DEBIT" */
  card_type: string;
  /** Issuing bank name */
  bank: string;
  /** ISO 3166-1 alpha-2 country code */
  country_code: string;
  /** Card brand */
  brand: string;
  /** Whether this authorization can be reused for future charges */
  reusable?: boolean;
  /** Paystack authorization signature; absent on some older events */
  signature?: string;
  /** Account name on the card; null if unavailable */
  account_name: string | null;
}

export interface PaystackWebhookCustomer {
  /** Paystack internal customer ID; absent on some older events */
  id?: number;
  /** Customer first name; null if not provided */
  first_name: string | null;
  /** Customer last name; null if not provided */
  last_name: string | null;
  /** Customer email address */
  email: string;
  /** Paystack customer code (CUS_xxx) */
  customer_code: string;
  /** Customer phone; null if not provided */
  phone: string | null;
  /** Arbitrary metadata stored on the customer */
  metadata: Record<string, unknown> | null;
  /** Paystack risk classification */
  risk_action: string;
  /** E.164 formatted phone; absent on older events */
  international_format_phone?: string | null;
}

export interface PaystackWebhookPlan {
  /** Paystack internal plan ID; absent on subscription.create */
  id?: number;
  /** Human-readable plan name */
  name: string;
  /** Paystack plan code (PLN_xxx) */
  plan_code: string;
  /** Plan description; null if not set */
  description: string | null;
  /** Recurring amount in kobo */
  amount: number;
  /** Billing interval e.g. "monthly", "annually" */
  interval: string;
  /** Whether Paystack sends invoice emails */
  send_invoices: boolean;
  /** Whether Paystack sends SMS notifications */
  send_sms: boolean;
  /** Plan currency */
  currency: string;
}

/** Subscription object nested inside invoice event payloads */
export interface PaystackWebhookNestedSubscription {
  /** Current subscription status */
  status: string;
  /** Subscription code (SUB_xxx) */
  subscription_code: string;
  /** Email token required for disable/enable; present on invoice.create, absent on invoice.update */
  email_token?: string;
  /** Recurring amount in kobo */
  amount: number;
  /** Cron expression for the billing schedule */
  cron_expression: string;
  /** ISO 8601 date of the next scheduled charge */
  next_payment_date: string | null;
  /** Invoice code of any currently open invoice; null if none */
  open_invoice: string | null;
}

/** Transaction object nested inside invoice event payloads */
export interface PaystackWebhookNestedTransaction {
  /** Transaction reference; absent on invoice.payment_failed with no charge attempt */
  reference?: string;
  /** Transaction status; absent if no charge was attempted */
  status?: string;
  /** Charged amount in kobo */
  amount?: number;
  /** Transaction currency */
  currency?: string;
}

// ---------------------------------------------------------------------------
// charge.success
// ---------------------------------------------------------------------------

export interface ChargeSuccessEventData {
  /** Paystack internal transaction ID — used to derive webhook idempotency key */
  id: number;
  /** Transaction reference */
  reference: string;
  /** Transaction status */
  status: 'success' | 'failed';
  /** Amount charged in kobo */
  amount: number;
  /** ISO 8601 timestamp when payment was completed */
  paid_at: string;
  /** Payment channel */
  channel: PaysatckChannels;
  /** Currency */
  currency: string;
  /** Card authorization — store authorization_code encrypted for subscription creation */
  authorization: PaystackWebhookAuthorization;
  /** Customer details */
  customer: PaystackWebhookCustomer;
  /** Arbitrary metadata set at transaction initialization */
  metadata: Record<string, unknown> | null;
  /** Paystack fees in kobo */
  fees: number;
}

export type ChargeSuccessEvent = PaystackWebhookEvent<ChargeSuccessEventData>;

// ---------------------------------------------------------------------------
// invoice.create / invoice.update / invoice.payment_failed
// ---------------------------------------------------------------------------

/** Shared data shape for all three invoice webhook events */
export interface InvoiceEventData {
  /** Environment: "live" or "test" */
  domain: string;
  /** Paystack invoice code (INV_xxx) */
  invoice_code: string;
  /** Invoice amount in kobo */
  amount: number;
  /** ISO 8601 billing period start */
  period_start: string;
  /** ISO 8601 billing period end */
  period_end: string;
  /** Invoice status e.g. "success", "pending" */
  status: string;
  /** Whether the invoice has been paid */
  paid: boolean;
  /** ISO 8601 timestamp when paid; null if unpaid */
  paid_at: string | null;
  /** Invoice description; null if not set */
  description: string | null;
  /** Card authorization used for this invoice */
  authorization: PaystackWebhookAuthorization;
  /** Associated subscription */
  subscription: PaystackWebhookNestedSubscription;
  /** Customer who was charged */
  customer: PaystackWebhookCustomer;
  /** Resulting transaction; may be empty object on payment_failed */
  transaction: PaystackWebhookNestedTransaction;
  /** ISO 8601 timestamp when the invoice was created */
  created_at: string;
}

export type InvoiceCreateEvent = PaystackWebhookEvent<InvoiceEventData>;
export type InvoiceUpdateEvent = PaystackWebhookEvent<InvoiceEventData>;
export type InvoicePaymentFailedEvent = PaystackWebhookEvent<InvoiceEventData>;

// ---------------------------------------------------------------------------
// subscription.create
// ---------------------------------------------------------------------------

export interface SubscriptionCreateEventData {
  /** Environment: "live" or "test" */
  domain: string;
  /** Subscription status */
  status: string;
  /** Subscription code (SUB_xxx) */
  subscription_code: string;
  /** Recurring amount in kobo */
  amount: number;
  /** Cron expression for the billing schedule */
  cron_expression: string;
  /** ISO 8601 date of the next scheduled charge */
  next_payment_date: string | null;
  /** Invoice code of any open invoice; null if none */
  open_invoice: string | null;
  /** ISO 8601 timestamp when the subscription was created on Paystack */
  createdAt: string;
  /** Plan details */
  plan: PaystackWebhookPlan;
  /** Card authorization backing this subscription */
  authorization: PaystackWebhookAuthorization;
  /** Customer who owns the subscription */
  customer: PaystackWebhookCustomer;
  /** ISO 8601 timestamp of this event */
  created_at: string;
}

export type SubscriptionCreateEvent = PaystackWebhookEvent<SubscriptionCreateEventData>;

// ---------------------------------------------------------------------------
// subscription.disable
// ---------------------------------------------------------------------------

export interface SubscriptionDisableEventData {
  /** Environment: "live" or "test" */
  domain: string;
  /** Subscription status at time of disable */
  status: string;
  /** Subscription code (SUB_xxx) */
  subscription_code: string;
  /** Email token — required to re-enable the subscription */
  email_token: string;
  /** Recurring amount in kobo */
  amount: number;
  /** Cron expression for the billing schedule */
  cron_expression: string;
  /** ISO 8601 next payment date; may be set even when disabled */
  next_payment_date: string | null;
  /** Invoice code of any open invoice; null if none */
  open_invoice: string | null;
  /** Plan details */
  plan: PaystackWebhookPlan;
  /** Card authorization backing this subscription */
  authorization: PaystackWebhookAuthorization;
  /** Customer who owns the subscription */
  customer: PaystackWebhookCustomer;
  /** ISO 8601 timestamp of this event */
  created_at: string;
}

export type SubscriptionDisableEvent = PaystackWebhookEvent<SubscriptionDisableEventData>;

// ---------------------------------------------------------------------------
// subscription.not_renew
// ---------------------------------------------------------------------------

export interface SubscriptionNotRenewEventData {
  /** Paystack internal subscription ID */
  id: number;
  /** Environment: "live" or "test" */
  domain: string;
  /** Subscription status — "non-renewing" */
  status: string;
  /** Subscription code (SUB_xxx) */
  subscription_code: string;
  /** Email token — required to re-enable the subscription */
  email_token: string;
  /** Recurring amount in kobo */
  amount: number;
  /** Cron expression for the billing schedule */
  cron_expression: string;
  /** ISO 8601 next payment date; null when set to not renew */
  next_payment_date: string | null;
  /** Invoice code of any open invoice; null if none */
  open_invoice: string | null;
  /** Paystack integration ID */
  integration: number;
  /** Plan details */
  plan: PaystackWebhookPlan;
  /** Card authorization backing this subscription */
  authorization: PaystackWebhookAuthorization;
  /** Customer who owns the subscription */
  customer: PaystackWebhookCustomer;
  /** Invoice list (usually empty on not_renew) */
  invoices: unknown[];
  /** Invoice history */
  invoices_history: unknown[];
  /** Maximum number of invoices */
  invoice_limit: number;
  /** Split code; null if not configured */
  split_code: string | null;
  /** Most recent invoice; null if none */
  most_recent_invoice: unknown | null;
  /** ISO 8601 timestamp when this subscription was originally created */
  created_at: string;
}

export type SubscriptionNotRenewEvent = PaystackWebhookEvent<SubscriptionNotRenewEventData>;

// ---------------------------------------------------------------------------
// Union type — use this in the webhook handler switch
// ---------------------------------------------------------------------------

export type PaystackEvent =
  | ChargeSuccessEvent
  | InvoiceCreateEvent
  | InvoiceUpdateEvent
  | InvoicePaymentFailedEvent
  | SubscriptionCreateEvent
  | SubscriptionDisableEvent
  | SubscriptionNotRenewEvent;
