// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: payment/payment.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "payment";

export interface Empty {
}

export interface OriginUrlReq {
  originUrl: string;
}

export interface CreateCheckoutSessionResponse {
  checkoutSessionUrl: string;
}

export interface CreatePortalSessionResponse {
  portalSessionUrl: string;
}

export const PAYMENT_PACKAGE_NAME = "payment";

export interface PaymentServiceClient {
  createCheckoutSession(request: OriginUrlReq, metadata?: Metadata): Observable<CreateCheckoutSessionResponse>;

  createPortalSession(request: OriginUrlReq, metadata?: Metadata): Observable<CreatePortalSessionResponse>;

  cancelSubscription(request: Empty, metadata?: Metadata): Observable<Empty>;
}

export interface PaymentServiceController {
  createCheckoutSession(
    request: OriginUrlReq,
    metadata?: Metadata,
  ): Promise<CreateCheckoutSessionResponse> | Observable<CreateCheckoutSessionResponse> | CreateCheckoutSessionResponse;

  createPortalSession(
    request: OriginUrlReq,
    metadata?: Metadata,
  ): Promise<CreatePortalSessionResponse> | Observable<CreatePortalSessionResponse> | CreatePortalSessionResponse;

  cancelSubscription(request: Empty, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;
}

export function PaymentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createCheckoutSession", "createPortalSession", "cancelSubscription"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYMENT_SERVICE_NAME = "PaymentService";
